language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
jobs:
  if: branch = master
  include:
    - env: MONGODB_ROLE="roles/mongodb_config"
    - env: MONGODB_ROLE="roles/mongodb_install"
    - env: MONGODB_ROLE="roles/mongodb_linux"
    - env: MONGODB_ROLE="roles/mongodb_mongod"
    - env: MONGODB_ROLE="roles/mongodb_mongos"
    - env: MONGODB_ROLE="roles/mongodb_repository"
    - env: MONGODB_ROLE="roles/mongodb_selinux"
before_install:
  - python --version
  - pip install --upgrade pip
  - export pyv=$(python -c 'from platform import python_version; print(python_version()[:3])')
  - pip install --requirement requirements-${pyv}.txt
  - ansible-galaxy collection install community.general
  - ansible-galaxy collection build
  - ansible-galaxy collection install community-mongodb-*.tar.gz
  - pip --version
  - ansible --version
  - molecule --version
  - pytest --version
script:
  - ./travis_run.sh
after_success:
  - codecov # submit coverage

