---
- name: Converge
  hosts: all
  roles:
    - role: mongodb_repository
      tags: molecule-idempotence-notest
    - role: mongodb_mongod
      vars:
        db_path: "/data/db"
        bind_ip: '"127.0.0.1,127.0.0.2,{{ ansible_default_ipv4.address }}"'

  tasks:

    - name: Install pymongo
      pip:
        name: "{{ 'pymongo==3.12.*' if ansible_python_version[0:3] | float < 3.6 else 'pymongo' }}"
      when: ansible_hostname == "fedora"

    - name: Determine openssl version
      command: openssl version
      changed_when: false
      register: openssl

    - name: Set mongosh package version
      set_fact:
        mongosh_package: "{{ 'mongodb-mongosh-shared-openssl3' if openssl.stdout.startswith('OpenSSL 3') else 'mongodb-mongosh-shared-openssl11' }}"
      when: mongosh_package is not defined

    - name: Install MongoDB Shell
      package:
        name:
          - "{{ mongosh_package }}"

    - name: Initialise replicaset
      community.mongodb.mongodb_replicaset:
        login_host: localhost
        replica_set: rs0
        validate: yes
        members:
          - almalinux_8:27017
          - fedora:27017
          - ubuntu_22_04:27017
          - debian_bullseye:27017
          - ubuntu_22:27017
      when: ansible_hostname == "fedora"
