---
- name: Converge
  hosts: all
  roles:
    - role: mongodb_repository
      tags: molecule-idempotence-notest
    - role: mongodb_config

  tasks:

    - name: Install pymongo
      pip:
        name: "{{ 'pymongo==3.12.*' if ansible_python_version[0:3] | float < 3.6 else 'pymongo' }}"
      when: ansible_hostname == "fedora"

    - name: Install MongoDB Shell
      package:
        name: mongodb-mongosh

    - name: Init config server replicaset
      community.mongodb.mongodb_replicaset:
        login_host: localhost
        login_port: 27019
        replica_set: cfg
        validate: no
        members:
          - almalinux_8:27019
          - fedora:27019
          - ubuntu_18:27019
          - debian_bullseye:27019
          - ubuntu_22:27019
      when: ansible_hostname == "fedora"
