---
- name: Prepare
  hosts: all
  become: yes
  vars:
    redhat_packages:
      - net-tools
  tasks:

  - name: Ensure epel is available
    ansible.builtin.package:
      name: epel-release
      state: present
    when:
      - ansible_os_family == "RedHat"
      - ansible_distribution != "Amazon"
      - ansible_distribution != "Fedora"

  - name: Install redhat packages
    ansible.builtin.package:
      name: "{{ redhat_packages }}"
      state: present
    when: ansible_os_family == "RedHat"