---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
  options:
    config-data:
      line-length: disable
platforms:
  - name: almalinux_8
    image: almalinux:8
  - name: ubuntu_18
    image: ubuntu:18.04
    privileged: yes
    command: "/sbin/init"
  - name: ubuntu_22
    image: ubuntu:22.04
    privileged: yes
    command: "/sbin/init"
  - name: debian_bullseye
    image: debian:bullseye
    privileged: yes
    command: "/sbin/init"
  - name: fedora
    image: fedora:37
provisioner:
  name: ansible
  lint:
    name: ansible-lint
    enabled: false
  inventory:
    host_vars:
      debian_bullseye:
        ansible_python_interpreter: /usr/bin/python3
      fedora:  # suitable for fedora 37
          redhat:
            rpm_key_key: "https://www.mongodb.org/static/pgp/server-{{ mongodb_version }}.asc"
            yum_baseurl: "https://repo.mongodb.org/yum/redhat/9/mongodb-org/{{ mongodb_version }}/x86_64/"
            yum_gpgkey: "https://www.mongodb.org/static/pgp/server-{{ mongodb_version }}.asc"
            yum_gpgcheck: true
            yum_description: "Official MongoDB {{ mongodb_version }} yum repo"        
verifier:
  name: testinfra
  lint:
    name: flake8
    options:
      ignore: 'E501'
