---
# tasks file for mongodb_mongod
- name: Include OS-specific vars
  include_vars:
    file: "{{ lookup('first_found', params) }}"
  vars:
    params:
      paths:
        - "vars"
      files:
        - "{{ ansible_facts.distribution }}-{{ ansible_facts.distribution_version }}.yml"
        - "{{ ansible_facts.os_family }}-{{ ansible_facts.distribution_major_version }}.yml"
        - "{{ ansible_facts.distribution }}.yml"
        - "{{ ansible_facts.os_family }}.yml"
        - default.yml

- name: Ensure mongod package is installed
  package:
    name: "{{ mongod_package }}"

- name: Ensure db_path dir exists
  file:
    path: "{{ db_path }}"
    state: directory
    owner: "{{ mongodb_user }}"
    group: "{{ mongodb_group }}"

- name: Copy config file
  template:
    src: mongod.conf.j2
    dest: /etc/mongod.conf
    owner: "{{ mongodb_user }}"
    group: "{{ mongodb_group }}"
  when:
    - not (ansible_facts.os_family == "RedHat" and ansible_facts.distribution_major_version|int == 8 and d.stat.exists == True)

- name: Copy config file (RH8 Docker)
  template:
    src: rh8_docker_mongod.conf.j2
    dest: /etc/mongod.conf
    owner: "{{ mongodb_user }}"
    group: "{{ mongodb_group }}"
  when:
    - ansible_facts.os_family == "RedHat" and ansible_facts.distribution_major_version|int == 8 and d.stat.exists == True

- name: Copy keyfile to host
  copy:
    content: |
      {{ openssl_keyfile_content }}
    dest: /etc/keyfile
    owner: "{{ mongodb_user }}"
    group: "{{ mongodb_group }}"
    mode: 0400
  when: authorization == "enabled"

#- name: Create systemd service file on RedHat 8+
#  copy:
#    dest: /etc/systemd/system/mongod.service
#    content: |
#      [Unit]
#      Description=MongoDB
#      After=syslog.target network.target
#
#      [Service]
#      Type=forking
#
#      User=mongod
#      Group=mongod
#
#      ExecStart=/usr/bin/mongod --config /etc/mongod.conf
#
#      [Install]
#      WantedBy=multi-user.target
#  register: systemd
#  when:
#    - ansible_facts.os_family == "RedHat"
#    - ansible_facts.distribution_major_version|int >= 8

#- name: Reload systemd
#  systemd:
#    daemon_reload: yes
#  when:
#    - ansible_facts.os_family == "RedHat"
#    - ansible_facts.distribution_major_version|int >= 8
#    - systemd is changed

- name: Are we in docker?
  stat:
    path: is_docker.txt
  register: d

- name: Start mongod service
  service:
    name: "{{ mongod_service }}"
    state: started
    enabled: yes
  when:
    - not (ansible_facts.os_family == "RedHat" and ansible_facts.distribution_major_version|int == 8 and d.stat.exists == True)

- name: Include tasks for RedHat 8 docker issue
  import_tasks: redhat_docker.yml
  when:
    - ansible_facts.os_family == "RedHat"
    - ansible_facts.distribution_major_version|int >= 8
    - d.stat.exists == True
